openapi: "3.0.0"
servers:
  - url: http://localhost:3000/api/v1
paths:
  /todos:
    get:
      summary: List todos
      operationId: GET_todos
      parameters: []
      responses:
        "200":
          description: An array of todos
    post:
      summary: Add new todo
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
            example:
              text: "create new workflow"
              completed: false
      responses:
        "200":
          description: OK
  /todos/{id}:
    get:
      summary: get a todo
      parameters:
        - name: id
          in: path
          description: todo's id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    delete:
      summary: delete a todo
      parameters:
        - name: id
          in: path
          description: todo's id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    post:
      summary: Update todo
      parameters:
        - name: id
          in: path
          description: todo's id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            example:
              text: "update old workflow"
              completed: true
      responses:
        "200":
          description: OK
    patch:
      summary: Update todo
      parameters:
        - name: id
          in: path
          description: todo's id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            example:
              text: "update old workflow"
              completed: true
      responses:
        "200":
          description: OK
components:
  schemas:
    Foo:
      additionalProperties: false
      properties:
        info:
          type: string
        myBool:
          type: boolean
        name:
          type: string
        someData:
          additionalProperties:
            format: uint
            minimum: 0.0
            type: integer
          type: object
      required:
        - info
        - myBool
        - name
        - someData
      type: object